const statesData = [
    { sl_no: 1, name: "Andaman and Nicobar Islands", alpha_code: "AN", gst_code: "35" },
    { sl_no: 2, name: "Andhra Pradesh", alpha_code: "AP", gst_code: "37" },
    { sl_no: 3, name: "Arunachal Pradesh", alpha_code: "AR", gst_code: "12" },
    { sl_no: 4, name: "Assam", alpha_code: "AS", gst_code: "18" },
    { sl_no: 5, name: "Bihar", alpha_code: "BR", gst_code: "10" },
    { sl_no: 6, name: "Chandigarh", alpha_code: "CH", gst_code: "04" },
    { sl_no: 7, name: "Chattisgarh", alpha_code: "CG", gst_code: "22" },
    { sl_no: 8, name: "Dadra and Nagar Haveli", alpha_code: "DN", gst_code: "26" },
    { sl_no: 9, name: "Daman and Diu", alpha_code: "DD", gst_code: "25" },
    { sl_no: 10, name: "Delhi", alpha_code: "DL", gst_code: "07" },
    { sl_no: 11, name: "Goa", alpha_code: "GA", gst_code: "30" },
    { sl_no: 12, name: "Gujarat", alpha_code: "GJ", gst_code: "24" },
    { sl_no: 13, name: "Haryana", alpha_code: "HR", gst_code: "06" },
    { sl_no: 14, name: "Himachal Pradesh", alpha_code: "HP", gst_code: "02" },
    { sl_no: 15, name: "Jammu and Kashmir", alpha_code: "JK", gst_code: "01" },
    { sl_no: 16, name: "Jharkhand", alpha_code: "JH", gst_code: "20" },
    { sl_no: 17, name: "Karnataka", alpha_code: "KA", gst_code: "29" },
    { sl_no: 18, name: "Kerala", alpha_code: "KL", gst_code: "32" },
    { sl_no: 19, name: "Ladakh", alpha_code: "LA", gst_code: "38" },
    { sl_no: 20, name: "Lakshadweep", alpha_code: "LD", gst_code: "31" },
    { sl_no: 21, name: "Madhya Pradesh", alpha_code: "MP", gst_code: "23" },
    { sl_no: 22, name: "Maharashtra", alpha_code: "MH", gst_code: "27" },
    { sl_no: 23, name: "Manipur", alpha_code: "MN", gst_code: "14" },
    { sl_no: 24, name: "Meghalaya", alpha_code: "ML", gst_code: "17" },
    { sl_no: 25, name: "Mizoram", alpha_code: "MZ", gst_code: "15" },
    { sl_no: 26, name: "Nagaland", alpha_code: "NL", gst_code: "13" },
    { sl_no: 27, name: "Odisha", alpha_code: "OR", gst_code: "21" },
    { sl_no: 28, name: "Other Territory", alpha_code: "OT", gst_code: "97" },
    { sl_no: 29, name: "Puducherry", alpha_code: "PY", gst_code: "34" },
    { sl_no: 30, name: "Punjab", alpha_code: "PB", gst_code: "03" },
    { sl_no: 31, name: "Rajasthan", alpha_code: "RJ", gst_code: "08" },
    { sl_no: 32, name: "Sikkim", alpha_code: "SK", gst_code: "11" },
    { sl_no: 33, name: "Tamil Nadu", alpha_code: "TN", gst_code: "33" },
    { sl_no: 34, name: "Telangana", alpha_code: "TS", gst_code: "36" },
    { sl_no: 35, name: "Tripura", alpha_code: "TR", gst_code: "16" },
    { sl_no: 36, name: "Uttar Pradesh", alpha_code: "UP", gst_code: "09" },
    { sl_no: 37, name: "Uttarakhand", alpha_code: "UA", gst_code: "05" },
    { sl_no: 38, name: "West Bengal", alpha_code: "WB", gst_code: "19" },
    { sl_no: 39, name: "Foreign Country", alpha_code: "FC", gst_code: "96" }
];

export default statesData;